name: Release PR

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Release PR
        uses: googleapis/release-please-action@v4
        with:
          release-type: go
